stages:
  - deploy-staging
  - deploy-production

cache:
  key: $CI_COMMIT_REF_NAME
  paths:
    - node_modules

deploy-staging:
  image: node:10.20.1
  stage: deploy-staging
  environment: staging
  before_script:
    - npm install -g firebase-tools --unsafe-perm
    - firebase use nmp-staging --token $FIREBASE_TOKEN
    - npm i
    - CI=false npm run build-dev
  script:
    - firebase deploy -m "Pipe $CI_PIPELINE_ID Build $CI_BUILD_ID" --only hosting --non-interactive --token $FIREBASE_TOKEN --debug
  only:
    - dev

deploy to production:
  stage: deploy-production
  environment: production
  image: agoncaruks/aws-elastic-beanstalk-cli
  before_script:
    - mkdir ~/.aws/
    - touch ~/.aws/credentials
    - printf "[nmpdev]\naws_access_key_id = %s\naws_secret_access_key = %s\n" "$AWS_ACCESS_KEY_ID" "$AWS_SECRET_ACCESS_KEY" >> ~/.aws/credentials
    - touch ~/.aws/config
    - printf "[profile nmpdev]\nregion=eu-west-2\noutput=json" >> ~/.aws/config
    - cp .ebenviroments/config.production.yml .elasticbeanstalk/config.yml
    - apt-get --yes --force-yes install curl
    - curl -sL https://deb.nodesource.com/setup_10.x | bash
    - apt-get --yes --force-yes install --yes --force-yes nodejs
  script:
    - git checkout master
    - cat .ebenviroments/https.production.conf >> .platform/nginx/conf.d/https.conf
    - npm i
    - CI=false npm run build-prod
    - cp -avr .platform build
    - cp -avr .elasticbeanstalk build
    - cd build
    - eb deploy NmpFeProdV1-env
  only:
    - master
