stages:
  - deploy-dev
  - deploy-staging
  - deploy-production

cache:
  key: $CI_COMMIT_REF_NAME
  paths:
    - node_modules

deploy to dev:
  stage: deploy-dev
  environment: dev
  image: agoncaruks/aws-elastic-beanstalk-cli
  before_script:
    - export NODE_OPTIONS=--max-old-space-size=8192
    - apt-get update --allow-releaseinfo-change
    - mkdir ~/.aws/
    - touch ~/.aws/credentials
    - printf "[nmpdev]\naws_access_key_id = %s\naws_secret_access_key = %s\n" "$AWS_ACCESS_KEY_ID" "$AWS_SECRET_ACCESS_KEY" >> ~/.aws/credentials
    - touch ~/.aws/config
    - printf "[profile nmpdev]\nregion=eu-west-2\noutput=json" >> ~/.aws/config
    - cp .ebenviroments/config.dev.yml .elasticbeanstalk/config.yml
    - apt-get --yes --force-yes install curl
    - curl -sL https://deb.nodesource.com/setup_14.x | bash
    - apt-get --yes --force-yes install --yes --force-yes nodejs
  script:
    - git checkout dev
    - cat .ebenviroments/https.dev.conf >> .platform/nginx/conf.d/https.conf
    - npm i
    - npm rebuild node-sass
    - CI=false npm run build-dev
    - cp -avr .platform build
    - cp -avr .elasticbeanstalk build
    - cd build
    - touch .ebignore
    - echo ".git/" >> .ebignore
    - eb deploy NmpFeDevV1-env
  only:
    - dev

deploy to staging:
  stage: deploy-staging
  environment: staging
  image: agoncaruks/aws-elastic-beanstalk-cli
  before_script:
    - export NODE_OPTIONS=--max-old-space-size=8192
    - apt-get update --allow-releaseinfo-change
    - mkdir ~/.aws/
    - touch ~/.aws/credentials
    - printf "[nmpdev]\naws_access_key_id = %s\naws_secret_access_key = %s\n" "$AWS_ACCESS_KEY_ID" "$AWS_SECRET_ACCESS_KEY" >> ~/.aws/credentials
    - touch ~/.aws/config
    - printf "[profile nmpdev]\nregion=eu-west-2\noutput=json" >> ~/.aws/config
    - cp .ebenviroments/config.staging.yml .elasticbeanstalk/config.yml
    - apt-get --yes --force-yes install curl
    - curl -sL https://deb.nodesource.com/setup_14.x | bash
    - apt-get --yes --force-yes install --yes --force-yes nodejs
  script:
    - git checkout staging
    - cat .ebenviroments/https.staging.conf >> .platform/nginx/conf.d/https.conf
    - npm i
    - npm rebuild node-sass
    - CI=false npm run build-stage
    - cp -avr .platform build
    - cp -avr .elasticbeanstalk build
    - cd build
    - touch .ebignore
    - echo ".git/" >> .ebignore
    - eb deploy NmpFeStageV1-env
  only:
    - staging

deploy to production:
  stage: deploy-production
  environment: production
  image: agoncaruks/aws-elastic-beanstalk-cli
  before_script:
    - export NODE_OPTIONS=--max-old-space-size=8192
    - apt-get update --allow-releaseinfo-change
    - mkdir ~/.aws/
    - touch ~/.aws/credentials
    - printf "[nmpdev]\naws_access_key_id = %s\naws_secret_access_key = %s\n" "$AWS_ACCESS_KEY_ID" "$AWS_SECRET_ACCESS_KEY" >> ~/.aws/credentials
    - touch ~/.aws/config
    - printf "[profile nmpdev]\nregion=eu-west-2\noutput=json" >> ~/.aws/config
    - cp .ebenviroments/config.production.yml .elasticbeanstalk/config.yml
    - apt-get --yes --force-yes install curl
    - curl -sL https://deb.nodesource.com/setup_14.x | bash
    - apt-get --yes --force-yes install --yes --force-yes nodejs
  script:
    - git checkout master
    - cat .ebenviroments/https.production.conf >> .platform/nginx/conf.d/https.conf
    - npm i
    - npm rebuild node-sass
    - CI=false npm run build-prod
    - cp -avr .platform build
    - cp -avr .elasticbeanstalk build
    - cd build
    - touch .ebignore
    - echo ".git/" >> .ebignore
    - eb deploy NmpFeProdV1-env
  only:
    - master
