branch-defaults:
  staging:
    environment: NmpFeStageV1-env
environment-defaults:
  NmpFeStageV1-env:
    branch: null
    repository: null
global:
  application_name: nmp-fe-stage-v1
  default_ec2_keyname: null
  default_platform: Node.js 14 running on 64bit Amazon Linux 2
  default_region: eu-west-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  sc: git
  workspace_type: Application
