export const getProfilePath =  "/api/user/profile";
export const getUsersPath =  "/api/user/getByEmail";
export const updateUserPath =  "/api/user";
export const updateUserRolesPath = (id) => `/api/user/${id}/roles`;
export const updateUserGroupsPath = (id) => `/api/user/${id}/groups`;
export const getUserAvatarPath =  "/api/file/user";
export const updateUserAvatarPath =  "/api/file/user";
export const deleteUserAvatarPath =  "/api/file";
export const getUsersDataPath = "api/user";
export const createUserOnboarding = "api/onboarding";
export const deleteUserOnboarding = "api/onboarding";